name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # ADD SIGNING STEPS HERE (REPLACE THE OLD BUILD STEPS)
    - name: Generate Signing Key
      run: |
        keytool -genkey -v -keystore app/counter-key.keystore -alias counter -keyalg RSA -keysize 2048 -validity 10000 -storepass password123 -keypass password123 -dname "CN=Counter App, OU=Dev, O=MyCompany, L=City, S=State, C=US"

    - name: Build and Sign APK
      run: |
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=counter-key.keystore \
          -Pandroid.injected.signing.store.password=password123 \
          -Pandroid.injected.signing.key.alias=counter \
          -Pandroid.injected.signing.key.password=password123

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: counter-app-signed
        path: app/build/outputs/apk/release/app-release.apk
